jpackage \
  --name PeriodCountdown \
  --input ./lib \
  --input ./json \
  --input ./src \
  --dest ./release/ \
  --verbose \
  --icon ./reference/icon.icns \
  --main-jar PeriodCountdown.jar \
  --main-class main.PeriodCountdown \
  --mac-package-name "Period Countdown"